### ISSUE TITLE
Add support for Serialized PHP data

### ISSUE THREAD

**Issue by derwentx** [facelessuser/SerializedDataConverter#10]
Hi there,
I just tried out your plugin and it does a great job of converting between the data formats.
I'm looking for a way to convert between serialized php data and JSON within Sublime Text 3, and I was wondering if you think it would be appropriate to add this to the plugin. 
I would be happy to write the necessary additions and submit a pull request if you think this would be a valuable addition to this plugin.
Thanks

**Comment by facelessuser** [comment]
I have no problem with it as long as you can get everything to convert over.  For instance, technically XML is serialized data, but it only converts well in PLIST form.  Straight XML isn't strictly typed data, so it makes it hard to convert over, especially with all the attributes an XML tag can have.

Obviously you know serialized PHP data better than I do.  As long as you find a way to convert everything over, I am fine with it.  But please pass serialized PHP data through the other converters as well, not just JSON.  Hopefully the conversion method has a nice intermediate form: like PHP data to Python dictionary.  That is basically how all the other converters work; maybe some additional post processing of the intermediate object before giving it to a specific converter to ensure compatibility of certain types when passing to a different converter.  Feel free to ask questions when you start digging in.

**Comment by derwentx** [comment]
Thanks Isaac,
I was thinking of using a python library like this one <https://pypi.python.org/pypi/phpserialize> to convert to a python object as an intermediary. I don’t know much about the other formats but this is a good opportunity to learn them so I’ll give them a go!
It may be a while before I have the free time to complete it but I’ll certainly give it a crack tomorrow morning and let you know how i go.
Cheers,




Derwent, 
Web Developer
laserphile.com <http://dev.laserphile.com/>

**Comment by facelessuser** [comment]
I will close this to clean out the issues as the question has been answered, but feel free to ask more questions here if any arise.

**Comment by simonhamp** [comment]
@derwentx did you ever get around to this?
